[package]
name = "edds_to_dds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
lz4 = "1.23.2"
lz4_flex = "0.9.2"
nom = "7.1.0"
